const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Behaviors.DragnDrop,
		C3.Plugins.video,
		C3.Plugins.Arr,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SaveState,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.video.Acts.Play,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{фонМеню: 0},
	{фон: 0},
	{вкладки_меню: 0},
	{открыть_алфавит: 0},
	{Тач: 0},
	{алфавит: 0},
	{нажата: 0},
	{кнопка_алф: 0},
	{закрыть_алф: 0},
	{фонПрочитай: 0},
	{дверь: 0},
	{желуди: 0},
	{ЛокальноеХранилище: 0},
	{Текст: 0},
	{кадр: 0},
	{перевернута: 0},
	{знач: 0},
	{cardмемо: 0},
	{Pin: 0},
	{LetterText: 0},
	{номер: 0},
	{разделы_вставьбукву: 0},
	{Мигание: 0},
	{ШРИФТКЛАВА: 0},
	{ПОЛЕВВОДА: 0},
	{один: 0},
	{два: 0},
	{три: 0},
	{четыре: 0},
	{пусто: 0},
	{Перетаскивание: 0},
	{Прикрепить: 0},
	{слово_пара: 0},
	{картинка_пара: 0},
	{поле_ответа_пара: 0},
	{ДИАЛОГ_ОКНО: 0},
	{шрифтАлфавит2: 0},
	{магазин: 0},
	{лес: 0},
	{дом: 0},
	{площадка: 0},
	{На_карту: 0},
	{ЗАПИСКА_иконка: 0},
	{записка: 0},
	{Спрайт2: 0},
	{алфавит_кадры: 0},
	{Видео: 0},
	{Текст2: 0},
	{Массив: 0},
	{СЛОВО1: 0},
	{ДвижениеК: 0},
	{СЛОВО2: 0},
	{СЛОВО3: 0},
	{СЛОВО4: 0},
	{ЧЕЛОВЕЧКИ: 0},
	{ГЛАЗ: 0},
	{слово_пара2: 0},
	{переход: 0},
	{продукты: 0},
	{галочка: 0},
	{текстДАКТИЛЬН: 0},
	{Спрайт: 0},
	{открытые_карты: 0},
	{карта1: 0},
	{карта1_UID: 0},
	{карта2_UID: 0},
	{карта1_кадр: 0},
	{карта2_кадр: 0},
	{i: 0},
	{счетчик: 0},
	{уровень: 0},
	{IsAlphabetVisible: 0},
	{CurrentAlphabetView: 0},
	{подуровень: 0},
	{рандом: 0},
	{один2: 0},
	{один3: 0},
	{один4: 0},
	{ЖЕЛУДИ: 0},
	{хлеб: 0},
	{молоко: 0},
	{яйца: 0},
	{помидоры: 0}
];

self.InstanceType = {
	фонМеню: class extends self.ISpriteInstance {},
	фон: class extends self.ISpriteInstance {},
	вкладки_меню: class extends self.ISpriteInstance {},
	открыть_алфавит: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	алфавит: class extends self.ISpriteInstance {},
	кнопка_алф: class extends self.ISpriteInstance {},
	закрыть_алф: class extends self.ISpriteInstance {},
	фонПрочитай: class extends self.ISpriteInstance {},
	дверь: class extends self.ISpriteInstance {},
	желуди: class extends self.ITextInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	cardмемо: class extends self.ISpriteInstance {},
	LetterText: class extends self.ITextInstance {},
	разделы_вставьбукву: class extends self.ISpriteInstance {},
	ШРИФТКЛАВА: class extends self.ISpriteFontInstance {},
	ПОЛЕВВОДА: class extends self.ISpriteInstance {},
	слово_пара: class extends self.ISpriteInstance {},
	картинка_пара: class extends self.ISpriteInstance {},
	поле_ответа_пара: class extends self.ISpriteInstance {},
	ДИАЛОГ_ОКНО: class extends self.ISpriteInstance {},
	шрифтАлфавит2: class extends self.ISpriteFontInstance {},
	магазин: class extends self.ISpriteInstance {},
	лес: class extends self.ISpriteInstance {},
	дом: class extends self.ISpriteInstance {},
	площадка: class extends self.ISpriteInstance {},
	На_карту: class extends self.ISpriteInstance {},
	ЗАПИСКА_иконка: class extends self.ISpriteInstance {},
	записка: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	алфавит_кадры: class extends self.ISpriteInstance {},
	Видео: class extends self.IWorldInstance {},
	Текст2: class extends self.ITextInstance {},
	Массив: class extends self.IArrayInstance {},
	СЛОВО1: class extends self.ISpriteFontInstance {},
	СЛОВО2: class extends self.ISpriteFontInstance {},
	СЛОВО3: class extends self.ISpriteFontInstance {},
	СЛОВО4: class extends self.ISpriteFontInstance {},
	ЧЕЛОВЕЧКИ: class extends self.ISpriteInstance {},
	ГЛАЗ: class extends self.ISpriteInstance {},
	слово_пара2: class extends self.ISpriteInstance {},
	переход: class extends self.ISpriteInstance {},
	продукты: class extends self.ISpriteInstance {},
	галочка: class extends self.ISpriteInstance {},
	текстДАКТИЛЬН: class extends self.ISpriteFontInstance {},
	Спрайт: class extends self.ISpriteInstance {}
}